# module5.py
# IoT Security Scanner - Module 5 (PDF Report Generator)
# Generates a professional PDF report saved to Desktop

import os
import datetime
from fpdf import FPDF


# ── PDF CONFIGURATION ──────────────────────────────────────────────────────────

COLORS = {
    'primary':    (0,   120, 215),    # Blue
    'critical':   (220, 50,  50),     # Red
    'high':       (255, 120, 0),      # Orange
    'weak':       (255, 200, 0),      # Yellow
    'safe':       (50,  180, 50),     # Green
    'white':      (255, 255, 255),    # White
    'black':      (0,   0,   0),      # Black
    'lightgray':  (240, 240, 240),    # Light Gray
    'darkgray':   (80,  80,  80),     # Dark Gray
}


# ── UNICODE SANITIZER ──────────────────────────────────────────────────────────
# fpdf2 with built-in fonts only supports Latin-1 (ISO-8859-1).
# This maps every common Unicode character that slips in from vendor APIs,
# UPnP data, or banner grabs to a safe ASCII equivalent.

_UNICODE_MAP = {
    '—': '--',   # em dash        —
    '–': '-',    # en dash        –
    '‒': '-',    # figure dash    ‒
    '‐': '-',    # hyphen         ‐
    '‘': "'",    # left quote     '
    '’': "'",    # right quote    '
    '“': '"',    # left dquote    "
    '”': '"',    # right dquote   "
    '…': '...',  # ellipsis       …
    '·': '*',    # middle dot     ·
    '•': '*',    # bullet         •
    '®': '(R)',  # registered     ®
    '©': '(C)',  # copyright      ©
    '°': 'deg',  # degree         °
    '±': '+/-',  # plus-minus     ±
    '×': 'x',    # multiply       ×
    '→': '->',   # right arrow    →
    '←': '<-',   # left arrow     ←
    '≤': '<=',   # less-equal     ≤
    '≥': '>=',   # greater-equal  ≥
}

def sanitize(text: str, max_len: int = None) -> str:
    """
    Replaces Unicode characters unsupported by Helvetica with ASCII equivalents.
    Drops any remaining non-Latin-1 characters safely.
    Optionally truncates to max_len.
    """
    if not text:
        return ''
    # Apply known replacements
    for uni, asc in _UNICODE_MAP.items():
        text = text.replace(uni, asc)
    # Drop anything still outside Latin-1
    text = text.encode('latin-1', errors='ignore').decode('latin-1')
    if max_len:
        text = text[:max_len]
    return text



# ── CUSTOM PDF CLASS ───────────────────────────────────────────────────────────

class SecurityReport(FPDF):

    def header(self):
        """Prints header on every page except cover."""
        if self.page_no() == 1:
            return

        # Header background
        self.set_fill_color(*COLORS['primary'])
        self.rect(0, 0, 210, 15, 'F')

        # Header text
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(*COLORS['white'])
        self.set_xy(10, 4)
        self.cell(0, 7, 'IoT Device Security Scanner - Confidential Report', ln=False)

        # Page number right side
        self.set_xy(-40, 4)
        self.cell(30, 7, f'Page {self.page_no()}', align='R')
        self.set_text_color(*COLORS['black'])
        self.ln(15)


    def footer(self):
        """Prints footer on every page."""
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*COLORS['darkgray'])
        scan_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        self.cell(0, 10, f'Generated by IoT Security Scanner | {scan_date}', align='C')


    def section_title(self, title):
        """Prints a styled section title."""
        self.set_fill_color(*COLORS['primary'])
        self.set_text_color(*COLORS['white'])
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 10, f'  {title}', ln=True, fill=True)
        self.set_text_color(*COLORS['black'])
        self.ln(3)


    def risk_color(self, risk):
        """Returns RGB color tuple for a risk level."""
        colors = {
            'CRITICAL': COLORS['critical'],
            'High':     COLORS['high'],
            'Weak':     COLORS['weak'],
            'Safe':     COLORS['safe'],
        }
        return colors.get(risk, COLORS['darkgray'])


# ── COVER PAGE ─────────────────────────────────────────────────────────────────

def add_cover_page(pdf, gateway, ip_range, score, score_label,
                   total_devices):
    """Generates the cover page."""
    pdf.add_page()

    # Background
    pdf.set_fill_color(*COLORS['primary'])
    pdf.rect(0, 0, 210, 297, 'F')

    # Title
    pdf.set_font('Helvetica', 'B', 28)
    pdf.set_text_color(*COLORS['white'])
    pdf.set_xy(0, 60)
    pdf.cell(210, 15, 'IoT Device Security Scanner', align='C', ln=True)

    pdf.set_font('Helvetica', '', 16)
    pdf.cell(210, 10, 'Network Security Assessment Report', align='C', ln=True)

    # Divider
    pdf.set_draw_color(*COLORS['white'])
    pdf.set_line_width(0.5)
    pdf.line(30, 95, 180, 95)
    pdf.ln(10)

    # Score box
    pdf.set_fill_color(*COLORS['white'])
    pdf.set_xy(55, 105)
    pdf.rect(55, 105, 100, 50, 'F')

    score_color = COLORS['critical'] if score < 50 else \
                  COLORS['high']     if score < 70 else \
                  COLORS['weak']     if score < 90 else \
                  COLORS['safe']

    pdf.set_font('Helvetica', 'B', 36)
    pdf.set_text_color(*score_color)
    pdf.set_xy(55, 112)
    pdf.cell(100, 20, f'{score}/100', align='C', ln=True)

    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(*COLORS['darkgray'])
    pdf.set_xy(55, 132)
    pdf.cell(100, 10, sanitize(f'Network Health: {score_label}'), align='C', ln=True)

    # Scan details
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(*COLORS['white'])
    pdf.set_xy(0, 170)

    scan_date = datetime.datetime.now().strftime("%B %d, %Y at %H:%M")
    pdf.cell(210, 8, sanitize(f'Scan Date    : {scan_date}'),         align='C', ln=True)
    pdf.cell(210, 8, sanitize(f'Gateway      : {gateway}'),           align='C', ln=True)
    pdf.cell(210, 8, sanitize(f'Network Range: {ip_range}'),          align='C', ln=True)
    pdf.cell(210, 8, sanitize(f'Devices Found: {total_devices}'),     align='C', ln=True)

    # Legal disclaimer — below scan details
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(255, 255, 180)
    pdf.set_xy(20, 220)
    pdf.multi_cell(170, 6,
        'LEGAL NOTICE: This tool is for authorised use only on networks you own '
        'or have explicit written permission to test. Unauthorised scanning of '
        'networks is illegal under the Computer Misuse Act 1990 and equivalent '
        'legislation worldwide. The authors accept no liability for misuse.',
        align='C'
    )

    # Footer note
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_xy(0, 260)
    pdf.cell(210, 8, 'CONFIDENTIAL - For authorized use only', align='C')
    pdf.set_text_color(*COLORS['black'])




# ── SUMMARY PAGE ───────────────────────────────────────────────────────────────

def add_summary_page(pdf, devices, score, score_label, breakdown, trend_img=None):
    """Generates the network summary page."""
    pdf.add_page()
    pdf.section_title('Network Summary')

    # Score overview
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(*COLORS['primary'])
    pdf.cell(0, 8, sanitize(f'Overall Network Health Score: {score}/100 ({score_label})'), ln=True)
    pdf.set_text_color(*COLORS['black'])
    pdf.ln(3)

    # Device counts
    critical = sum(1 for d in devices if d['risk'] == 'CRITICAL')
    high     = sum(1 for d in devices if d['risk'] == 'High')
    weak     = sum(1 for d in devices if d['risk'] == 'Weak')
    safe     = sum(1 for d in devices if d['risk'] == 'Safe')

    # Count boxes
    box_data = [
        ('CRITICAL', critical, COLORS['critical']),
        ('HIGH',     high,     COLORS['high']),
        ('WEAK',     weak,     COLORS['weak']),
        ('SAFE',     safe,     COLORS['safe']),
    ]

    x_start = 10
    for label, count, color in box_data:
        pdf.set_fill_color(*color)
        pdf.set_text_color(*COLORS['white'])
        pdf.set_xy(x_start, pdf.get_y())
        pdf.set_font('Helvetica', 'B', 20)
        pdf.cell(42, 18, str(count), align='C', fill=True)
        pdf.set_xy(x_start, pdf.get_y())
        pdf.set_font('Helvetica', '', 8)
        pdf.cell(42, 6, label, align='C', fill=True, ln=False)
        x_start += 48

    pdf.set_text_color(*COLORS['black'])
    pdf.ln(12)

    # Score breakdown table
    pdf.ln(3)
    pdf.section_title('Score Breakdown')

    # Table header
    pdf.set_fill_color(*COLORS['primary'])
    pdf.set_text_color(*COLORS['white'])
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(60, 8, 'IP Address',  fill=True, border=1)
    pdf.cell(100, 8, 'Reason',     fill=True, border=1)
    pdf.cell(30, 8, 'Impact',      fill=True, border=1, ln=True)

    # Table rows
    pdf.set_font('Helvetica', '', 9)
    fill = False
    for b in breakdown:
        deduction = b['deduction']
        is_reward = deduction < 0   # negative deduction = bonus points

        pdf.set_fill_color(*COLORS['lightgray'] if fill else COLORS['white'])
        pdf.set_text_color(*COLORS['black'])
        pdf.cell(60,  8, sanitize(b['ip']),     fill=True, border=1)
        pdf.cell(100, 8, sanitize(b['reason']), fill=True, border=1)

        # Rewards show green "+X pts", penalties show red "-X pts"
        if is_reward:
            pdf.set_text_color(*COLORS['safe'])
            pdf.cell(30, 8, f"+{abs(deduction)} pts", fill=True, border=1, ln=True)
        else:
            pdf.set_text_color(*COLORS['critical'])
            pdf.cell(30, 8, f"-{deduction} pts",      fill=True, border=1, ln=True)

        fill = not fill

    # Risk trend graph — embedded below breakdown table if available
    if trend_img and os.path.exists(trend_img):
        pdf.ln(6)
        pdf.section_title('Network Score - Historical Trend')
        pdf.image(trend_img, x=10, w=188)


# ── DEVICES PAGE ───────────────────────────────────────────────────────────────

def add_devices_page(pdf, devices):
    """Generates the full device details page."""
    pdf.add_page()
    pdf.section_title('Device Details')

    # Table header
    pdf.set_fill_color(*COLORS['primary'])
    pdf.set_text_color(*COLORS['white'])
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(30, 8, 'IP Address',   fill=True, border=1)
    pdf.cell(38, 8, 'MAC Address',  fill=True, border=1)
    pdf.cell(38, 8, 'Vendor',       fill=True, border=1)
    pdf.cell(28, 8, 'Device Type',  fill=True, border=1)
    pdf.cell(34, 8, 'UPnP Model',   fill=True, border=1)
    pdf.cell(22, 8, 'Risk Level',   fill=True, border=1, ln=True)

    # Table rows
    pdf.set_font('Helvetica', '', 8)
    fill = False
    for d in devices:
        risk        = d.get('risk', 'Safe')
        risk_color  = pdf.risk_color(risk)
        vendor      = d.get('display_name', d.get('vendor_api', d.get('vendor', 'Unknown')))[:20]
        device_type = d.get('device_type', 'Unknown')[:16]
        upnp        = d.get('upnp', {})
        upnp_model  = (upnp.get('friendly_name') or upnp.get('model') or 'N/A')[:18]

        bg = COLORS['lightgray'] if fill else COLORS['white']
        pdf.set_fill_color(*bg)
        pdf.set_text_color(*COLORS['black'])

        pdf.cell(30, 8, sanitize(d['ip']),        fill=True, border=1)
        pdf.cell(38, 8, sanitize(d['mac']),       fill=True, border=1)
        pdf.cell(38, 8, sanitize(vendor),         fill=True, border=1)
        pdf.cell(28, 8, sanitize(device_type),    fill=True, border=1)
        pdf.cell(34, 8, sanitize(upnp_model),     fill=True, border=1)

        # Risk cell with color
        pdf.set_fill_color(*risk_color)
        pdf.set_text_color(*COLORS['white'])
        pdf.cell(22, 8, sanitize(risk), fill=True, border=1, ln=True)

        pdf.set_text_color(*COLORS['black'])
        fill = not fill

    # Open ports per device
    pdf.ln(5)
    pdf.section_title('Open Ports Per Device')

    for d in devices:
        ip         = d['ip']
        vendor     = d.get('display_name', d.get('vendor_api', d.get('vendor', 'Unknown')))
        open_ports = d.get('open_ports', [])

        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(*COLORS['primary'])
        pdf.cell(0, 7, sanitize(f'{ip} - {vendor}'), ln=True)
        pdf.set_text_color(*COLORS['black'])

        if not open_ports:
            pdf.set_font('Helvetica', 'I', 9)
            pdf.cell(0, 6, '  No dangerous ports open', ln=True)
        else:
            pdf.set_font('Helvetica', '', 9)
            for port in open_ports:
                from module1 import get_port_name
                pdf.cell(0, 6,
                    sanitize(f'  * Port {port} ({get_port_name(port)})'),
                    ln=True
                )
        pdf.ln(2)


# ── CVE PAGE ───────────────────────────────────────────────────────────────────

def add_cve_page(pdf, devices, cve_results):
    """Generates the CVE vulnerabilities page."""
    pdf.add_page()
    pdf.section_title('Known Vulnerabilities (CVE Lookup)')

    for device in devices:
        ip     = device['ip']
        vendor = device.get('display_name', device.get('vendor_api', device.get('vendor', 'Unknown')))
        cves   = cve_results.get(ip, [])

        # Device header
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(*COLORS['primary'])
        pdf.cell(0, 7, sanitize(f'{ip} - {vendor}'), ln=True)
        pdf.set_text_color(*COLORS['black'])

        if not cves:
            pdf.set_font('Helvetica', 'I', 9)
            pdf.set_text_color(*COLORS['safe'])
            pdf.cell(0, 6, '  No known CVEs found', ln=True)
            pdf.set_text_color(*COLORS['black'])
        else:
            # CVE table header
            pdf.set_fill_color(*COLORS['primary'])
            pdf.set_text_color(*COLORS['white'])
            pdf.set_font('Helvetica', 'B', 9)
            pdf.cell(40,  7, 'CVE ID',      fill=True, border=1)
            pdf.cell(25,  7, 'Severity',    fill=True, border=1)
            pdf.cell(125, 7, 'Description', fill=True, border=1, ln=True)

            pdf.set_text_color(*COLORS['black'])
            pdf.set_font('Helvetica', '', 8)
            fill = False

            for cve in cves:
                severity       = cve.get('severity', 'N/A')
                severity_color = COLORS['critical'] if severity == 'CRITICAL' else \
                                 COLORS['high']     if severity == 'HIGH'     else \
                                 COLORS['weak']     if severity == 'MEDIUM'   else \
                                 COLORS['darkgray']

                bg = COLORS['lightgray'] if fill else COLORS['white']
                pdf.set_fill_color(*bg)
                pdf.cell(40,  7, sanitize(cve.get('id', 'N/A')),          fill=True, border=1)

                pdf.set_fill_color(*severity_color)
                pdf.set_text_color(*COLORS['white'])
                pdf.cell(25,  7, sanitize(severity),                       fill=True, border=1)

                pdf.set_fill_color(*bg)
                pdf.set_text_color(*COLORS['black'])
                desc = cve.get('description', '')[:80]
                pdf.cell(125, 7, sanitize(desc),                           fill=True, border=1, ln=True)
                fill = not fill

        pdf.ln(4)


# ── RED TEAM PAGE ──────────────────────────────────────────────────────────────

def add_redteam_page(pdf, m4_results):
    """Generates the red team results page."""
    pdf.add_page()
    pdf.section_title('Red Team Assessment Results')

    for device in m4_results:
        ip      = device['ip']
        vendor  = device.get('display_name', device.get('vendor_api', device.get('vendor', 'Unknown')))
        verdict = device['verdict']
        tests   = device['tests']

        # Device header
        verdict_color = COLORS['critical'] if verdict == 'COMPROMISED' else COLORS['safe']
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(*COLORS['primary'])
        pdf.cell(130, 7, sanitize(f'{ip} - {vendor}'), ln=False)
        pdf.set_fill_color(*verdict_color)
        pdf.set_text_color(*COLORS['white'])
        pdf.cell(60, 7, sanitize(f'VERDICT: {verdict}'), fill=True, align='C', ln=True)
        pdf.set_text_color(*COLORS['black'])

        if not tests:
            pdf.set_font('Helvetica', 'I', 9)
            pdf.cell(0, 6, '  No testable ports found', ln=True)
        else:
            pdf.set_font('Helvetica', '', 9)
            for test_name, result in tests.items():
                if result.get('compromised'):
                    status = f"COMPROMISED - {result.get('credential') or result.get('stream_url', '')}"
                    pdf.set_text_color(*COLORS['critical'])
                elif not result.get('tested'):
                    status = "Port Closed - Skipped"
                    pdf.set_text_color(*COLORS['darkgray'])
                else:
                    status = "Secure - Login Rejected"
                    pdf.set_text_color(*COLORS['safe'])

                pdf.cell(0, 6, sanitize(f'  [{test_name.upper():10s}] {status}'), ln=True)
                pdf.set_text_color(*COLORS['black'])

        pdf.ln(3)


# ── RECOMMENDATIONS PAGE ───────────────────────────────────────────────────────

def add_recommendations_page(pdf, recommendations):
    """Generates the fix recommendations page."""
    pdf.add_page()
    pdf.section_title('Security Recommendations')

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*COLORS['darkgray'])
    pdf.cell(0, 7,
        'The following actions are recommended to improve your network security:',
        ln=True
    )
    pdf.ln(3)

    if not recommendations:
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(*COLORS['safe'])
        pdf.cell(0, 10, 'No issues found. Your network looks secure.', ln=True)
        return

    for rec in recommendations:
        # Device header
        pdf.set_fill_color(*COLORS['lightgray'])
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(*COLORS['primary'])
        pdf.cell(0, 8,
            sanitize(f"  Device: {rec['ip']} ({rec.get('display_name', rec.get('vendor', 'Unknown'))})"),
            fill=True, ln=True
        )
        pdf.set_text_color(*COLORS['black'])

        # Fixes
        pdf.set_font('Helvetica', '', 9)
        for i, fix in enumerate(rec['fixes'], 1):
            # Word wrap long fixes
            pdf.set_x(15)
            pdf.multi_cell(0, 6, sanitize(f'{i}. {fix}'))

        pdf.ln(3)


# ── LEGAL DISCLAIMER PAGE ──────────────────────────────────────────────────────

def add_disclaimer_page(pdf):
    """Generates a full legal disclaimer page (Page 7)."""
    pdf.add_page()
    pdf.section_title('Legal Disclaimer & Authorised Use Policy')

    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(*COLORS['critical'])
    pdf.cell(0, 8, 'IMPORTANT - READ BEFORE USE', ln=True)
    pdf.set_text_color(*COLORS['black'])
    pdf.ln(2)

    sections = [
        (
            'Authorised Use Only',
            'This IoT Device Security Scanner is designed exclusively for use on networks '
            'that you own or have received explicit written permission to test. Running this '
            'tool against any network without proper authorisation is strictly prohibited.'
        ),
        (
            'Legal Compliance',
            'Unauthorised network scanning and penetration testing is a criminal offence '
            'under the Computer Misuse Act 1990 (UK), the Computer Fraud and Abuse Act (USA), '
            'and equivalent legislation in most jurisdictions worldwide. Violations may result '
            'in prosecution, fines, and imprisonment.'
        ),
        (
            'Scope of Consent',
            'Each use of the active penetration testing module (Module 4) requires explicit '
            'user consent, which is recorded in the audit log with a timestamp. This consent '
            'applies only to the specific network scanned during that session and does not '
            'constitute blanket authorisation for future scans.'
        ),
        (
            'Limitation of Liability',
            'The developers of this tool accept no responsibility or liability for any damage, '
            'data loss, service disruption, or legal consequences arising from the misuse of '
            'this software. Use entirely at your own risk.'
        ),
        (
            'Data Handling',
            'All scan results, device data, and vulnerability information are stored locally '
            'on your machine in scanner_history.db. No data is transmitted to external servers. '
            'The PDF report generated is marked CONFIDENTIAL and should be treated accordingly.'
        ),
        (
            'Responsible Disclosure',
            'If this scanner reveals vulnerabilities in devices you do not own, you are '
            'encouraged to follow responsible disclosure practices and notify the device '
            'manufacturer or network owner through appropriate channels.'
        ),
    ]

    for heading, body in sections:
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_fill_color(*COLORS['lightgray'])
        pdf.cell(0, 7, f'  {heading}', fill=True, ln=True)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_x(15)
        pdf.multi_cell(175, 6, body)
        pdf.ln(2)

    # Signature block
    pdf.ln(5)
    pdf.set_draw_color(*COLORS['darkgray'])
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(*COLORS['darkgray'])
    pdf.cell(0, 6,
        'By using this software you confirm that you have read, understood, and agree '
        'to the terms above.',
        ln=True, align='C'
    )
    pdf.set_text_color(*COLORS['black'])


# ── ETHICS & AUDIT PAGE ────────────────────────────────────────────────────────

def add_ethics_page(pdf):
    """
    Generates the ethics audit trail page (Page 8).
    Reads audit_log.txt and displays all recorded consent timestamps.
    """
    pdf.add_page()
    pdf.section_title('Ethics Compliance & Consent Audit Trail')

    # Introduction
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*COLORS['darkgray'])
    pdf.multi_cell(0, 7,
        'This scanner follows a strict consent-before-exploit model. '
        'Active penetration testing (Module 4) only executes after the user '
        'explicitly confirms authorisation. Every consent event is recorded '
        'below with a precise timestamp for accountability and audit purposes.'
    )
    pdf.ln(5)

    # Ethical principles box
    pdf.section_title('Ethical Design Principles')
    principles = [
        ('Informed Consent',   'User must explicitly approve active exploitation before Module 4 runs.'),
        ('Minimal Footprint',  'Only ports confirmed open by Module 1 are tested - no blind probing.'),
        ('No Silent Scanning', 'Module 4 never runs in --monitor or --report modes without consent.'),
        ('Local Data Only',    'All results stored locally. No data sent to external servers.'),
        ('Audit Logging',      'Every consent event is written to audit_log.txt with a timestamp.'),
        ('Transparency',       'All tests are disclosed in the PDF report with full result details.'),
    ]

    pdf.set_font('Helvetica', '', 9)
    fill = False
    for principle, description in principles:
        bg = COLORS['lightgray'] if fill else COLORS['white']
        pdf.set_fill_color(*bg)
        pdf.set_font('Helvetica', 'B', 9)
        pdf.cell(50, 7, f'  {principle}', fill=True, border=1)
        pdf.set_font('Helvetica', '', 9)
        pdf.cell(140, 7, description, fill=True, border=1, ln=True)
        fill = not fill

    pdf.ln(6)
    pdf.section_title('Recorded Consent Events (audit_log.txt)')

    # Read audit log
    audit_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), 'audit_log.txt'
    )

    if not os.path.exists(audit_path):
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(*COLORS['darkgray'])
        pdf.cell(0, 8,
            'No audit log found. Module 4 has not been run in this session.',
            ln=True
        )
        pdf.set_text_color(*COLORS['black'])
        return

    try:
        with open(audit_path, 'r', encoding='utf-8') as f:
            lines = [l.strip() for l in f.readlines() if l.strip()]
    except Exception as e:
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(*COLORS['critical'])
        pdf.cell(0, 8, f'Error reading audit log: {e}', ln=True)
        pdf.set_text_color(*COLORS['black'])
        return

    if not lines:
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(*COLORS['darkgray'])
        pdf.cell(0, 8, 'Audit log exists but contains no entries.', ln=True)
        pdf.set_text_color(*COLORS['black'])
        return

    # Table header
    pdf.set_fill_color(*COLORS['primary'])
    pdf.set_text_color(*COLORS['white'])
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(15,  8, '#',         fill=True, border=1)
    pdf.cell(55,  8, 'Timestamp', fill=True, border=1)
    pdf.cell(120, 8, 'Event',     fill=True, border=1, ln=True)

    # Table rows
    pdf.set_text_color(*COLORS['black'])
    pdf.set_font('Helvetica', '', 8)
    fill = False
    for i, line in enumerate(lines, 1):
        # Parse "[YYYY-MM-DD HH:MM:SS] message" format
        timestamp = ''
        event     = line
        if line.startswith('[') and ']' in line:
            bracket_end = line.index(']')
            timestamp   = line[1:bracket_end]
            event       = line[bracket_end + 2:].strip()

        bg = COLORS['lightgray'] if fill else COLORS['white']
        pdf.set_fill_color(*bg)
        pdf.cell(15,  8, str(i),          fill=True, border=1)
        pdf.cell(55,  8, sanitize(timestamp[:22]),  fill=True, border=1)
        pdf.cell(120, 8, sanitize(event[:65]),      fill=True, border=1, ln=True)
        fill = not fill

    # Summary
    pdf.ln(4)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(*COLORS['safe'])
    pdf.set_text_color(*COLORS['white'])
    pdf.cell(0, 8,
        f'  Total consent events recorded: {len(lines)}',
        fill=True, ln=True
    )
    pdf.set_text_color(*COLORS['black'])


# ── MASTER FUNCTION ────────────────────────────────────────────────────────────

def run_module5(gateway, ip_range, m2_results, m3_data, m4_results):
    """
    Generates the complete PDF security report.
    Saves to Desktop automatically.

    Args:
        gateway    (str):  Router IP
        ip_range   (str):  Network range scanned
        m2_results (list): Enriched device list from Module 2
        m3_data    (dict): Assessment data from Module 3
        m4_results (list): Red team results from Module 4

    Returns:
        str: Full path to saved PDF file
    """
    # ── Generate visual images ────────────────────────────────────────────────
    trend_img = None

    try:
        from visuals import generate_trend_graph, cleanup_images
        print("  Generating risk trend graph...")
        db_path   = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "scanner_history.db")
        trend_img = generate_trend_graph(db_path)
        if not trend_img:
            print("  Trend graph skipped — need at least 2 scans in history.")
    except ImportError:
        print("  [!] matplotlib/networkx not installed — skipping visuals.")
        print("      Run: pip install matplotlib networkx")
    except Exception as e:
        print(f"  [!] Visual generation error: {e}")

    # ── Build PDF ─────────────────────────────────────────────────────────────
    pdf = SecurityReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(10, 20, 10)

    score       = m3_data['score']
    score_label = m3_data['score_label']
    breakdown   = m3_data['breakdown']
    cve_results = m3_data['cve_results']
    recs        = m3_data['recommendations']

    # Build all pages
    add_cover_page(pdf,
        gateway, ip_range,
        score, score_label,
        len(m2_results)
    )
    add_summary_page(pdf, m2_results, score, score_label, breakdown,
                     trend_img = trend_img)
    add_devices_page(pdf,  m2_results)
    add_cve_page(pdf,      m2_results, cve_results)
    add_redteam_page(pdf,  m4_results)
    add_recommendations_page(pdf, recs)
    add_disclaimer_page(pdf)
    add_ethics_page(pdf)

    # ── Save to Desktop ───────────────────────────────────────────────────────
    desktop  = os.path.join(os.path.expanduser("~"), "Desktop")
    date_str = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M")
    filename = f"WiFi_Security_Report_{date_str}.pdf"
    filepath = os.path.join(desktop, filename)

    pdf.output(filepath)

    # ── Clean up temp PNG files ────────────────────────────────────────────────
    try:
        from visuals import cleanup_images
        cleanup_images(trend_img)
    except Exception:
        pass

    return filepath